"""add audit_logs

Revision ID: 6d20843f1363
Revises: cc9b4907806e
Create Date: 2025-12-28 12:56:28.072730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d20843f1363'
down_revision: Union[str, None] = 'cc9b4907806e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_service_packages_id', table_name='service_packages')
    op.drop_table('service_packages')
    op.drop_index('ix_checklist_templates_id', table_name='checklist_templates')
    op.drop_table('checklist_templates')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lawyer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('helper_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('required', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lawyer_id'], ['lawyers.id'], name='checklist_templates_lawyer_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='checklist_templates_pkey')
    )
    op.create_index('ix_checklist_templates_id', 'checklist_templates', ['id'], unique=False)
    op.create_table('service_packages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lawyer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lawyer_id'], ['lawyers.id'], name='service_packages_lawyer_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='service_packages_pkey')
    )
    op.create_index('ix_service_packages_id', 'service_packages', ['id'], unique=False)
    # ### end Alembic commands ###

















